# Welcome to lab_🐼s!

Last week, you did amazing work setting up your computer for the rest of the semester! Now, let's use your computer to do data science for the first time!

A few tips to remember:

- **You are not alone on your journey in learning programming!**  You have your lab Teaching Assistant (TA), your Course Assistants (CAs), your lab group, and the professors (Prof. Karle and Prof. Wade), who are all here to help you out!
- If you find yourself stuck for more than a few minutes, ask a neighbor or course staff for help!  When you are giving help to your neighbor, explain the **idea and approach** to the problem without sharing the answer itself so they can have the same **<i>ah-hah</i>** moment!
- We are here to help you!  Don't feel embarrassed or shy to ask us for help!

Let's get started!

<hr style="color: #DD3403;">

# Part 0: Your Lab Group!

We find that it's best to program with a group of people so everyone can help each other out!

- A key part of Data Science is being able to **communicate about the work you've done**. By learning strong communication skills, you will be able to **explain your code**, and the underlying data science concepts, to everyone -- data scientists and non-scientists alike!

- **Every lab** you will need to complete some parts of the lab **with your group**. There will be both **"group discussion questions"** and **"individual written reflection questions"** as part of every lab.

## Create Your Group

If you have not done so already, **RIGHT NOW** find people to make a group of **two, three, or four** people (we find that groups of 3 are ideal). 

- If you're at a group of five, split into a group of two and a group of three. You can still help each other as a larger group, but the group questions should be answered in your smaller group of 2-4 people.

Once you have your group, **introduce yourselves to each other! :)**

## Record Your Group

Since you know Python, edit the following cell to add strings about your group:

In [1]:
# First, meet your CAs and TA if you haven't already!
# ...first name is enough, we'll know who they are! :)
ta_name = "Mehmet"
ca1_name = "Bella"
ca2_name = "jonah"
ca3_name = ""


# As part of your introduction, learn your lab partner's name, major, and
# learn something new about them that you never knew!
partner1_name = "Alex"
partner1_netid = "acere2"
partner1_major = "ETMASCM"

partner2_name = ""
partner2_netid = ""
partner2_major = ""

partner3_name = ""
partner3_netid = ""
partner3_major = ""

# Which lab section are you in? Record it below! It should start with a Y and have 
# 2 numbers after the Y. If you're unsure - ask your TA/CAs!
lab_section = "Y05"

<hr style="color: #DD3403;">

# Part 1: 🧑‍🤝‍🧑 Hello Dataset!

In lecture, we have started to explore the "Party Words Dataset" that you created. We will continue to use the Party Words Dataset all semester long, but we want even more datasets -- and we want you to come up with the questions!

In this lab, **you and your group members** will come up with questions to ask the entire class to create the **"Hello Dataset"**!

## Hello Dataset Overview

This upcoming weekend, your lab homework will be to fill out a class-wide "Hello Survey".  Right now, with your group, you will come up some of the questions that should be on this survey *(and you will do analysis on your questions next week!)*.

With your group, come up with four questions below!  Before you get started, a few notes:

- The survey will be **NOT be anonymous** and the results will be shared with the class to do analysis on, so you should **only ask questions you feel comfortable sharing with the class**.
- **Questions that are inappropriate** for a classroom environment will be thrown out and you won't earn points for any question we throw out. (Keep everything at most PG/PG-13.)
- You are going to submit **one set of questions for your whole group** and you must decide on the questions together.

## Q1: Question with a Binary Response

A question with a **binary response** is a question that has only two answers.  For example:
- *Do you prefer cats or dogs?*
- *Were you born in Illinois?*

With your group, come up with one question that you think will have **exactly 50%/50%** split between the two binary outcomes.  *(The question that gets closest to 50%/50% will get extra credit!)*

**What is your binary question?**

*(Would you rather go to the gym in the morning or afternoon?)*

**Why do you think this is a good question?  Write at least two complete sentences on why you believe your question will have a 50%/50% split.**

*(This question will have a 50%/50% split because some people don't want to wake up early before classes to go the gym, and on the other hand other people don't have time to go to the gym in the afternoon.)*

## Q2: Question with a Numeric Response

A question with a **numeric response** requires a number for an answer.  For example:

- *What is your height in inches?*
- *What day were you born?*

With your group, come up with a single numeric response question. Also, include a prediction on what you think the most frequent answer will be to your question.

**What is your numeric question?**

*(How many pets do you have?)*

**What do you think the most frequent answer will be?**

*(1)*

**Why do you think this answer will be the most frequent answer?  Write at least one complete sentence on why you believe that it will be the most frequent answer.**

*(We believe this will be the most frequent answer because most people think having more than 1 pet is too much work.)*

## Q3: Question with a (non-numeric) Textual Response

A question with a (non-numeric) **textual response** requires a word or two for an answer.  For example:

- *What is your favorite sport to play?*
- *What is the location of your favorite trip/vacation?*

With your group, come up with a single textual response question where at least two members of your group share the same answer.

**What is your textual response question?**

*(What city are you from?)*

**What is the shared answer between your group?  Do you also share this answer (if not, what's your answer to the question)?**

*(Chicago)*

## Q4: Open Question

One final question -- no restrictions on the format!  Is there a great question your group discussed that you did not get to use as one of the first three questions but you want to know the class's answer?

**What is your final question for the whole class?**

*(Where do you live on campus?)*

## Submit Your Questions to Professors Wade and Karle

Your lab TAs will be grading your lab notebook for your full responses, but we want to make sure to get the survey with your questions out to everyone ASAP!

- Pick one member of your group as the "question submitter".
- If you're the question submitter, complete this Google Form for your group (requires @illinois.edu login): https://docs.google.com/forms/d/e/1FAIpQLSfQ0XKPQXwRXEtA9OKmO2Ty8_yVrcARIO1l8qk7merHGDhdQg/viewform?usp=sharing&ouid=103660412360957657789 
- Make sure to do this **during your lab section**.

## This Weekend: Complete the "Hello Survey"

On Friday evening, we will post the "Hello Survey" on Canvas with the questions you (and the entire class) asked.  You will have to complete this before **Monday, Sept. 8th** and it will be part of your lab grade.

<hr style="color: #DD3403;">

# Part 2: Importing the Course Catalog Dataset

In lecture, you learned that we will use the `pandas` **library** for working with data. Libraries are collections of functions and other objects that extend what Python can do by itself.  The `pandas` library is the most widely used library for data science.

To use the `pandas` library, we must **import** it into your notebook.  In every lab, you will need to import the library just like we did in lecture!

In the following cell, replace `...` with the code to import pandas as `pd`:

In [2]:
# Write the code to import pandas as pd:
import pandas as pd

In lecture, you saw the "Course Catalog" dataset.  Using the `read_csv` function, load the course catalog dataset.  The URL for this dataset is:
```
http://waf-server-01.cs.illinois.edu/static/course-catalog.csv
```

Remember, URLs passed to `read_csv` are **string** variables, so remember to use **quotation marks**. 

> **macOS users**: If you are running macOS, you may get a HTTPS connection security-related error.  If you get this error, there's a solution for you on the Canvas lab overview page!! :)

In [5]:
# Load the course catalog dataset into a variable named `df`:
df = pd.read_csv("http://waf-server-01.cs.illinois.edu/static/course-catalog.csv")

In [6]:
# Look at `df` to confirm that this worked:
df

,Year,Term,YearTerm,Subject,Number,Name,Description,Credit Hours,Section Info,Degree Attributes,...,Section Status,Enrollment Status,Type,Type Code,Start Time,End Time,Days of Week,Room,Building,Instructors
0,2025,Spring,2025-sp,AAS,100,Intro Asian American Studies,Interdisciplinary introduction to the basic co...,3 hours.,NaN,"Social & Beh Sci - Soc Sci, and Cultural Studi...",...,A,Closed,Lecture-Discussion,LCD,02:00 PM,03:20 PM,MW,304,Noyes Laboratory,"Geng, C"
1,2025,Spring,2025-sp,AAS,100,Intro Asian American Studies,Interdisciplinary introduction to the basic co...,3 hours.,NaN,"Social & Beh Sci - Soc Sci, and Cultural Studi...",...,A,Open,Discussion/Recitation,DIS,09:00 AM,09:50 AM,F,1030,"Literatures, Cultures, & Ling","Siglos, D;Wang, Y"
2,2025,Spring,2025-sp,AAS,100,Intro Asian American Studies,Interdisciplinary introduction to the basic co...,3 hours.,NaN,"Social & Beh Sci - Soc Sci, and Cultural Studi...",...,A,Open,Discussion/Recitation,DIS,10:00 AM,10:50 AM,F,1030,"Literatures, Cultures, & Ling","Siglos, D;Wang, Y"
3,2025,Spring,2025-sp,AAS,100,Intro Asian American Studies,Interdisciplinary introduction to the basic co...,3 hours.,NaN,"Social & Beh Sci - Soc Sci, and Cultural Studi...",...,A,Open,Discussion/Recitation,DIS,11:00 AM,11:50 AM,F,1030,"Literatures, Cultures, & Ling","Kim, G;Siglos, D"
4,2025,Spring,2025-sp,AAS,100,Intro Asian American Studies,Interdisciplinary introduction to the basic co...,3 hours.,NaN,"Social & Beh Sci - Soc Sci, and Cultural Studi...",...,A,Open,Discussion/Recitation,DIS,12:00 PM,12:50 PM,F,1030,"Literatures, Cultures, & Ling","Kim, G;Siglos, D"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12316,2025,Spring,2025-sp,WRIT,303,Writing Across Media,Same as INFO 303. See INFO 303.,3 hours.,Same as INFO 303. See INFO 303.,Advanced Composition course.,...,A,Closed,Lecture,LEC,11:00 AM,12:15 PM,TR,204,Transportation Building,"Liu, N"
12317,2025,Spring,2025-sp,WRIT,303,Writing Across Media,Same as INFO 303. See INFO 303.,3 hours.,Same as INFO 303. See INFO 303.,Advanced Composition course.,...,A,Closed,Lecture,LEC,12:30 PM,01:45 PM,TR,11,Psychology Building,"Kapczynski, L"
12318,2025,Spring,2025-sp,YDSH,102,Beginning Yiddish II,Continuation of YDSH 101 focusing on comprehen...,4 hours.,NaN,NaN,...,A,Closed,Online,ONL,09:00 AM,10:00 AM,F,NaN,NaN,"Butler, D"
12319,2025,Spring,2025-sp,YDSH,102,Beginning Yiddish II,Continuation of YDSH 101 focusing on comprehen...,4 hours.,NaN,NaN,...,A,Closed,Online,ONL,09:00 AM,10:30 AM,TR,NaN,NaN,"Butler, D"
12320,2025,Spring,2025-sp,YDSH,320,Responses to the Holocaust,"Same as CWL 320, ENGL 359, JS 320, and REL 320...",3 hours.,"Same as CWL 320, ENGL 359, JS 320, and REL 320...","Humanities - Lit & Arts, and Cultural Studies ...",...,A,CrossListOpen,Lecture-Discussion,LCD,12:30 PM,01:50 PM,TR,1306,Everitt Laboratory,"Grossman, R"

## 🔬 Test Case Checkpoint 🔬

Throughout the lab, we will have "checkpoints" at key points.  Most checkpoints will include **test cases** that verify that your notebook appears to be correct.

- The test cases are **NOT** a guarantee that everything is perfect, but we try our very best to catch any common mistakes you might make!
- If you see `AssertionError` error message when running the test case, we provide a helpful hint on what may not be correct.
- If you see a party popper emoji and a message that all tests pass, you passed the checkpoint!
- **Checkpoints** are a good time to check with your group to make everyone gets to the checkpoint together!

In [7]:
## == CHECKPOINT TEST CASES for Part 1 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.
assert( 'df' in vars() ), "Did you define a variable called df?"
assert( len(df) == 12321 ), "It looks like you did not import the correct dataset?"


## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

<hr style="color: #DD3403;">

# Part 3: STAT / CS / IS Majors

Data Science DISCOVERY is a unique course that is cross-listed across three departments: Statistics, Computer Science, and Information Sciences.  Let's explore courses from all three of those subjects!

### Puzzle 3.1

Select only the rows that have a `Subject` of `STAT`.  Assign this to the variable name `df_STAT` instead of the usual `df`.
- Make sure your result contains only statistics courses!

In [9]:
df_STAT = df[df.Subject == "STAT"]
df_STAT

,Year,Term,YearTerm,Subject,Number,Name,Description,Credit Hours,Section Info,Degree Attributes,...,Section Status,Enrollment Status,Type,Type Code,Start Time,End Time,Days of Week,Room,Building,Instructors
11549,2025,Spring,2025-sp,STAT,100,Statistics,First course in probability and statistics at ...,3 hours.,Credit is not given for both STAT 100 and any ...,Quantitative Reasoning I course.,...,A,Open (Restricted),Lecture,LEC,02:00 PM,02:50 PM,MWF,THEAT,Lincoln Hall,"Rao, V"
11550,2025,Spring,2025-sp,STAT,100,Statistics,First course in probability and statistics at ...,3 hours.,Credit is not given for both STAT 100 and any ...,Quantitative Reasoning I course.,...,A,Closed,Online,ONL,ARRANGED,NaN,NaN,NaN,NaN,"Rao, V"
11551,2025,Spring,2025-sp,STAT,107,Data Science Discovery,Data Science Discovery is the intersection of ...,4 hours.,Same as CS 107 and IS 107.,Quantitative Reasoning I course.,...,A,CrossListOpen (Restricted),Lecture,LEC,10:00 AM,10:50 AM,MWF,THEAT,Lincoln Hall,"Fagen-Ulmschneider, W;Flanagan, K"
11552,2025,Spring,2025-sp,STAT,107,Data Science Discovery,Data Science Discovery is the intersection of ...,4 hours.,Same as CS 107 and IS 107.,Quantitative Reasoning I course.,...,A,CrossListOpen (Restricted),Lecture,LEC,12:00 PM,12:50 PM,MWF,THEAT,Lincoln Hall,"Fagen-Ulmschneider, W;Flanagan, K"
11553,2025,Spring,2025-sp,STAT,107,Data Science Discovery,Data Science Discovery is the intersection of ...,4 hours.,Same as CS 107 and IS 107.,Quantitative Reasoning I course.,...,A,CrossListOpen,Laboratory-Discussion,LBD,11:00 AM,12:20 PM,R,G20,"Literatures, Cultures, & Ling",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11710,2025,Spring,2025-sp,STAT,587,Hierarchical Linear Models,Same as PSYC 587 and EPSY 587. See EPSY 587.,4 hours.,Same as PSYC 587 and EPSY 587. See EPSY 587.,NaN,...,A,Closed,Lecture,LEC,02:00 PM,03:20 PM,MW,242,Education Building,"Zhang, J"
11711,2025,Spring,2025-sp,STAT,590,Individual Study and Research,Directed reading and research. Approved for le...,0 TO 8 hours.,Approved for letter and S/U grading. May be re...,NaN,...,A,Closed,Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,NaN
11712,2025,Spring,2025-sp,STAT,593,STAT Internship,"Supervised, off-campus experience in a field i...",0 TO 8 hours.,Approved for letter and S/U grading. Prerequis...,NaN,...,A,Open (Restricted),Internship,INT,ARRANGED,NaN,NaN,NaN,NaN,"Chronopoulou, A;Glosemeyer, D;Lee, H;Shao, X;U..."
11713,2025,Spring,2025-sp,STAT,593,STAT Internship,"Supervised, off-campus experience in a field i...",0 TO 8 hours.,Approved for letter and S/U grading. Prerequis...,NaN,...,A,Open (Restricted),Internship,INT,ARRANGED,NaN,NaN,NaN,NaN,"Chronopoulou, A;Glosemeyer, D;Lee, H;Shao, X;U..."
11714,2025,Spring,2025-sp,STAT,599,Thesis Research,Approved for S/U grading only. May be repeated...,0 TO 16 hours.,Approved for S/U grading only. May be repeated...,NaN,...,A,Closed,Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,NaN

### Puzzle 3.2

Select only the rows that have a `Subject` of `CS`.  Assign this to the variable name `df_CS` instead of the usual `df`.
- Make sure your result contains only computer science courses!

In [10]:
df_CS = df[df.Subject == "CS"]
df_CS

,Year,Term,YearTerm,Subject,Number,Name,Description,Credit Hours,Section Info,Degree Attributes,...,Section Status,Enrollment Status,Type,Type Code,Start Time,End Time,Days of Week,Room,Building,Instructors
2997,2025,Spring,2025-sp,CS,101,Intro Computing: Engrg &amp; Sci,"Fundamental principles, concepts, and methods ...",3 hours.,Prerequisite: One of MATH 220 or MATH 221 or M...,Quantitative Reasoning II course.,...,A,Open (Restricted),Lecture,LEC,03:00 PM,03:50 PM,MW,AUD,Foellinger Auditorium,"Butler, L;Ritschel, N"
2998,2025,Spring,2025-sp,CS,101,Intro Computing: Engrg &amp; Sci,"Fundamental principles, concepts, and methods ...",3 hours.,Prerequisite: One of MATH 220 or MATH 221 or M...,Quantitative Reasoning II course.,...,A,Closed,Laboratory-Discussion,LBD,04:00 PM,05:50 PM,M,432,Armory,"Butler, L;Ritschel, N"
2999,2025,Spring,2025-sp,CS,101,Intro Computing: Engrg &amp; Sci,"Fundamental principles, concepts, and methods ...",3 hours.,Prerequisite: One of MATH 220 or MATH 221 or M...,Quantitative Reasoning II course.,...,A,Closed,Laboratory-Discussion,LBD,09:00 AM,10:50 AM,T,2406,Siebel Center for Comp Sci,"Butler, L;Ritschel, N"
3000,2025,Spring,2025-sp,CS,101,Intro Computing: Engrg &amp; Sci,"Fundamental principles, concepts, and methods ...",3 hours.,Prerequisite: One of MATH 220 or MATH 221 or M...,Quantitative Reasoning II course.,...,A,Open,Laboratory-Discussion,LBD,11:00 AM,12:50 PM,T,2406,Siebel Center for Comp Sci,"Butler, L;Ritschel, N"
3001,2025,Spring,2025-sp,CS,101,Intro Computing: Engrg &amp; Sci,"Fundamental principles, concepts, and methods ...",3 hours.,Prerequisite: One of MATH 220 or MATH 221 or M...,Quantitative Reasoning II course.,...,A,Closed,Laboratory-Discussion,LBD,01:00 PM,02:50 PM,T,2406,Siebel Center for Comp Sci,"Butler, L;Ritschel, N"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3414,2025,Spring,2025-sp,CS,598,Special Topics,Subject offerings of new and developing areas ...,2 TO 4 hours.,May be repeated in the same or separate terms ...,NaN,...,A,Closed,Lecture,LEC,12:30 PM,01:50 PM,TR,3020,Electrical & Computer Eng Bldg,"Gupta, S"
3415,2025,Spring,2025-sp,CS,598,Special Topics,Subject offerings of new and developing areas ...,2 TO 4 hours.,May be repeated in the same or separate terms ...,NaN,...,A,Closed,Lecture-Discussion,S17,09:30 AM,10:45 AM,TR,218,Siebel Center for Comp Sci,"August, T"
3416,2025,Spring,2025-sp,CS,598,Special Topics,Subject offerings of new and developing areas ...,2 TO 4 hours.,May be repeated in the same or separate terms ...,NaN,...,A,Closed,Lecture-Discussion,S13,11:00 AM,12:15 PM,WF,218,Siebel Center for Comp Sci,"Yuan, W"
3417,2025,Spring,2025-sp,CS,598,Special Topics,Subject offerings of new and developing areas ...,2 TO 4 hours.,May be repeated in the same or separate terms ...,NaN,...,A,Closed,Lecture-Discussion,S5,02:00 PM,03:15 PM,TR,1310,Digital Computer Laboratory,"Park, Y"
3418,2025,Spring,2025-sp,CS,599,Thesis Research,Approved for S/U grading only. May be repeated.,0 TO 16 hours.,Approved for S/U grading only. May be repeated.,NaN,...,A,Closed,Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,NaN

### Puzzle 3.3

Select only the rows that have a `Subject` of `IS`.  Assign this to the variable name `df_IS` instead of the usual `df`.
- Make sure your result contains only information science courses!

In [11]:
df_IS = df[df.Subject == "IS"]
df_IS

,Year,Term,YearTerm,Subject,Number,Name,Description,Credit Hours,Section Info,Degree Attributes,...,Section Status,Enrollment Status,Type,Type Code,Start Time,End Time,Days of Week,Room,Building,Instructors
6404,2025,Spring,2025-sp,IS,100,Exploring the iSchool with a Human-Centered Lens,This course introduces students to the School ...,1 hours.,Prerequisite: Restricted to Majors Only; First...,NaN,...,A,Open (Restricted),Lecture-Discussion,LCD,11:00 AM,11:50 AM,T,126,Grad Sch of Lib & Info Science,"Kittl, K"
6405,2025,Spring,2025-sp,IS,101,Introduction to Information Sciences,This course provides an introduction to the fi...,3 hours.,NaN,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,11:00 AM,12:20 PM,R,12A,Grad Sch of Lib & Info Science,"Pintar, J"
6406,2025,Spring,2025-sp,IS,101,Introduction to Information Sciences,This course provides an introduction to the fi...,3 hours.,NaN,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,11:00 AM,12:20 PM,R,53,Grad Sch of Lib & Info Science,"Pintar, J"
6407,2025,Spring,2025-sp,IS,101,Introduction to Information Sciences,This course provides an introduction to the fi...,3 hours.,NaN,Social & Beh Sci - Soc Sci course.,...,A,Open (Restricted),Discussion/Recitation,DIS,09:30 AM,10:50 AM,R,12A,Grad Sch of Lib & Info Science,"Pintar, J"
6408,2025,Spring,2025-sp,IS,101,Introduction to Information Sciences,This course provides an introduction to the fi...,3 hours.,NaN,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,12:30 PM,01:50 PM,R,12A,Grad Sch of Lib & Info Science,"Pintar, J"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6732,2025,Spring,2025-sp,IS,599,Thesis Research,Individual study and research. 0 to 16 graduat...,0 TO 16 hours.,0 to 16 graduate hours. No professional credit...,NaN,...,A,Open,Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,"Torvik, V"
6733,2025,Spring,2025-sp,IS,599,Thesis Research,Individual study and research. 0 to 16 graduat...,0 TO 16 hours.,0 to 16 graduate hours. No professional credit...,NaN,...,A,Open,Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,"Underwood, W"
6734,2025,Spring,2025-sp,IS,599,Thesis Research,Individual study and research. 0 to 16 graduat...,0 TO 16 hours.,0 to 16 graduate hours. No professional credit...,NaN,...,A,Open,Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,"Huang, Y"
6735,2025,Spring,2025-sp,IS,599,Thesis Research,Individual study and research. 0 to 16 graduat...,0 TO 16 hours.,0 to 16 graduate hours. No professional credit...,NaN,...,A,Open,Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,"Wang, Y"
6736,2025,Spring,2025-sp,IS,599,Thesis Research,Individual study and research. 0 to 16 graduat...,0 TO 16 hours.,0 to 16 graduate hours. No professional credit...,NaN,...,A,Open,Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,"LeBlanc, Z"

### 🔬 Test Case Checkpoint 🔬

In [12]:
## == CHECKPOINT TEST CASES for Part 3 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.
assert( 'df_CS' in vars() ), "Make certain to name the CS courses df_CS."
assert( 'df_STAT' in vars() ), "Make certain to name the STAT courses df_STAT."
assert( 'df_IS' in vars() ), "Make certain to name the IS courses df_IS."
assert( len(df_STAT[df_STAT.Subject != "STAT"] ) == 0 ), "It looks like you did not subset df_STAT to only STAT courses."
assert( len(df_CS[df_CS.Subject != "CS"] ) == 0 ), "It looks like you did not subset df_CS to only CS courses."
assert( len(df_IS[df_IS.Subject != "IS"] ) == 0 ), "It looks like you did not subset df_IS to only IS courses."
assert( len(df_STAT) == 166 ), "It looks like you do not subset df_STAT correctly. Check your conditional statement."
assert( len(df_CS) == 422 ), "It looks like you do not subset df_CS correctly. Check your conditional statement."
assert( len(df_IS) == 333 ), "It looks like you do not subset df_IS correctly. Check your conditional statement."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

<hr style="color: #DD3403;">

# Part 4: Your Major

In this part, you will be exploring **your major** using the Course Catalog dataset. This dataset contains sections of each course at UIUC.

- Use the primary subject of your **current major** (or, if you're undeclared, your intended major) for this section.
- Your answers will be different than the rest of your group!

### Puzzle 4.1:

Select only the rows that have a `Subject` of your current/intended major.  Assign this to the variable name `mydf` instead of `df`:

In [14]:
mydf = df[df.Subject == "ECON"]
mydf

,Year,Term,YearTerm,Subject,Number,Name,Description,Credit Hours,Section Info,Degree Attributes,...,Section Status,Enrollment Status,Type,Type Code,Start Time,End Time,Days of Week,Room,Building,Instructors
4124,2025,Spring,2025-sp,ECON,102,Microeconomic Principles,Introduction to the functions of individual de...,3 hours.,Credit is not given for ECON 102 and ACE 100.,Social & Beh Sci - Soc Sci course.,...,A,Open,Discussion/Recitation,DIS,08:00 AM,08:50 AM,F,215B,David Kinley Hall,"Buckley, B;Wang, X"
4125,2025,Spring,2025-sp,ECON,102,Microeconomic Principles,Introduction to the functions of individual de...,3 hours.,Credit is not given for ECON 102 and ACE 100.,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,09:00 AM,09:50 AM,F,215B,David Kinley Hall,"Buckley, B;Wang, X"
4126,2025,Spring,2025-sp,ECON,102,Microeconomic Principles,Introduction to the functions of individual de...,3 hours.,Credit is not given for ECON 102 and ACE 100.,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,10:00 AM,10:50 AM,F,215B,David Kinley Hall,"Buckley, B;Wang, X"
4127,2025,Spring,2025-sp,ECON,102,Microeconomic Principles,Introduction to the functions of individual de...,3 hours.,Credit is not given for ECON 102 and ACE 100.,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,11:00 AM,11:50 AM,F,215B,David Kinley Hall,"Buckley, B;Wang, X"
4128,2025,Spring,2025-sp,ECON,102,Microeconomic Principles,Introduction to the functions of individual de...,3 hours.,Credit is not given for ECON 102 and ACE 100.,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,12:00 PM,12:50 PM,F,215B,David Kinley Hall,"Buckley, B;Buller, D"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4344,2025,Spring,2025-sp,ECON,598,Workshop and Research Seminar,Workshops are offered in all areas of speciali...,2 hours.,Approved for S/U grading only. May be repeated...,NaN,...,A,Open (Restricted),Conference,CNF,02:00 PM,03:20 PM,MW,317,David Kinley Hall,"Yoo, H"
4345,2025,Spring,2025-sp,ECON,598,Workshop and Research Seminar,Workshops are offered in all areas of speciali...,2 hours.,Approved for S/U grading only. May be repeated...,NaN,...,A,Open (Restricted),Conference,C8,02:00 PM,03:20 PM,T,317,David Kinley Hall,"Howard, G"
4346,2025,Spring,2025-sp,ECON,598,Workshop and Research Seminar,Workshops are offered in all areas of speciali...,2 hours.,Approved for S/U grading only. May be repeated...,NaN,...,A,Open (Restricted),Conference,C2,02:00 PM,03:20 PM,R,317,David Kinley Hall,"Durandard, T"
4347,2025,Spring,2025-sp,ECON,598,Workshop and Research Seminar,Workshops are offered in all areas of speciali...,2 hours.,Approved for S/U grading only. May be repeated...,NaN,...,A,Open (Restricted),Conference,C5,02:00 PM,03:20 PM,F,317,David Kinley Hall,"Shea, J"
4348,2025,Spring,2025-sp,ECON,599,Thesis Research,Preparation of thesis required of all students...,0 TO 16 hours.,Approved for S/U grading only. May be repeated.,NaN,...,A,Open (Restricted),Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,NaN

### Puzzle 4.2:

Select **five random course sections** from your major, using `mydf` and pandas functions:

In [16]:
mydf.sample(n=5)

,Year,Term,YearTerm,Subject,Number,Name,Description,Credit Hours,Section Info,Degree Attributes,...,Section Status,Enrollment Status,Type,Type Code,Start Time,End Time,Days of Week,Room,Building,Instructors
4186,2025,Spring,2025-sp,ECON,103,Macroeconomic Principles,Introduction to the theory of determination of...,3 hours.,NaN,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,08:00 AM,08:50 AM,R,429,Armory,"Niu, M;Vazquez, J"
4208,2025,Spring,2025-sp,ECON,203,Economic Statistics II,Continuation of ECON 202. Builds upon point an...,3 hours.,Students must have completed a course on proba...,NaN,...,A,Closed,Laboratory,LAB,12:00 PM,12:50 PM,F,144,Armory,"Jeziorski, W;Song, H"
4190,2025,Spring,2025-sp,ECON,198,Economics at Illinois,An introductory course intended to help studen...,1 hours.,Approved for S/U grading only.,NaN,...,A,Open (Restricted),Lecture,LEC,01:00 PM,01:50 PM,T,120,Architecture Building,"Kennealy - Pierczynski, K"
4287,2025,Spring,2025-sp,ECON,490,Topics in Economics,Special topics in advanced economics within a ...,3 OR 4 hours.,3 undergraduate hours. 4 graduate hours. May b...,NaN,...,A,Open (Restricted),Lecture-Discussion,S2,03:30 PM,04:50 PM,TR,215B,David Kinley Hall,"Stocker, A"
4178,2025,Spring,2025-sp,ECON,103,Macroeconomic Principles,Introduction to the theory of determination of...,3 hours.,NaN,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,01:00 PM,01:50 PM,R,147,Armory,"Hoque, M;Vazquez, J"

### Puzzle 4.3:

Select **the seven course sections with the smallest course number** from your major:

In [17]:
mydf.head(7)

,Year,Term,YearTerm,Subject,Number,Name,Description,Credit Hours,Section Info,Degree Attributes,...,Section Status,Enrollment Status,Type,Type Code,Start Time,End Time,Days of Week,Room,Building,Instructors
4124,2025,Spring,2025-sp,ECON,102,Microeconomic Principles,Introduction to the functions of individual de...,3 hours.,Credit is not given for ECON 102 and ACE 100.,Social & Beh Sci - Soc Sci course.,...,A,Open,Discussion/Recitation,DIS,08:00 AM,08:50 AM,F,215B,David Kinley Hall,"Buckley, B;Wang, X"
4125,2025,Spring,2025-sp,ECON,102,Microeconomic Principles,Introduction to the functions of individual de...,3 hours.,Credit is not given for ECON 102 and ACE 100.,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,09:00 AM,09:50 AM,F,215B,David Kinley Hall,"Buckley, B;Wang, X"
4126,2025,Spring,2025-sp,ECON,102,Microeconomic Principles,Introduction to the functions of individual de...,3 hours.,Credit is not given for ECON 102 and ACE 100.,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,10:00 AM,10:50 AM,F,215B,David Kinley Hall,"Buckley, B;Wang, X"
4127,2025,Spring,2025-sp,ECON,102,Microeconomic Principles,Introduction to the functions of individual de...,3 hours.,Credit is not given for ECON 102 and ACE 100.,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,11:00 AM,11:50 AM,F,215B,David Kinley Hall,"Buckley, B;Wang, X"
4128,2025,Spring,2025-sp,ECON,102,Microeconomic Principles,Introduction to the functions of individual de...,3 hours.,Credit is not given for ECON 102 and ACE 100.,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,12:00 PM,12:50 PM,F,215B,David Kinley Hall,"Buckley, B;Buller, D"
4129,2025,Spring,2025-sp,ECON,102,Microeconomic Principles,Introduction to the functions of individual de...,3 hours.,Credit is not given for ECON 102 and ACE 100.,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,01:00 PM,01:50 PM,F,215B,David Kinley Hall,"Buckley, B;Buller, D"
4130,2025,Spring,2025-sp,ECON,102,Microeconomic Principles,Introduction to the functions of individual de...,3 hours.,Credit is not given for ECON 102 and ACE 100.,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,02:00 PM,02:50 PM,F,215B,David Kinley Hall,"Buckley, B;Liu, S"

### Puzzle 4.4:

Select **the nine course sections with the highest course number** from your major:

In [18]:
mydf.tail(9)

,Year,Term,YearTerm,Subject,Number,Name,Description,Credit Hours,Section Info,Degree Attributes,...,Section Status,Enrollment Status,Type,Type Code,Start Time,End Time,Days of Week,Room,Building,Instructors
4340,2025,Spring,2025-sp,ECON,590,Individual Study and Research,Directed reading and research. Approved for bo...,0 TO 4 hours.,Approved for both letter and S/U grading. May ...,NaN,...,A,Open (Restricted),Lecture-Discussion,S6,11:00 AM,12:20 PM,TR,215B,David Kinley Hall,"Wu, J"
4341,2025,Spring,2025-sp,ECON,590,Individual Study and Research,Directed reading and research. Approved for bo...,0 TO 4 hours.,Approved for both letter and S/U grading. May ...,NaN,...,A,Open (Restricted),Seminar,SEM,12:30 PM,01:50 PM,TR,317,David Kinley Hall,"Osman, A"
4342,2025,Spring,2025-sp,ECON,590,Individual Study and Research,Directed reading and research. Approved for bo...,0 TO 4 hours.,Approved for both letter and S/U grading. May ...,NaN,...,A,Open (Restricted),Seminar,SEM,12:30 PM,01:50 PM,R,223,David Kinley Hall,"Xie, S"
4343,2025,Spring,2025-sp,ECON,590,Individual Study and Research,Directed reading and research. Approved for bo...,0 TO 4 hours.,Approved for both letter and S/U grading. May ...,NaN,...,A,Open (Restricted),Seminar,M1,03:30 PM,05:20 PM,MWF,317,David Kinley Hall,"Bernhardt, M"
4344,2025,Spring,2025-sp,ECON,598,Workshop and Research Seminar,Workshops are offered in all areas of speciali...,2 hours.,Approved for S/U grading only. May be repeated...,NaN,...,A,Open (Restricted),Conference,CNF,02:00 PM,03:20 PM,MW,317,David Kinley Hall,"Yoo, H"
4345,2025,Spring,2025-sp,ECON,598,Workshop and Research Seminar,Workshops are offered in all areas of speciali...,2 hours.,Approved for S/U grading only. May be repeated...,NaN,...,A,Open (Restricted),Conference,C8,02:00 PM,03:20 PM,T,317,David Kinley Hall,"Howard, G"
4346,2025,Spring,2025-sp,ECON,598,Workshop and Research Seminar,Workshops are offered in all areas of speciali...,2 hours.,Approved for S/U grading only. May be repeated...,NaN,...,A,Open (Restricted),Conference,C2,02:00 PM,03:20 PM,R,317,David Kinley Hall,"Durandard, T"
4347,2025,Spring,2025-sp,ECON,598,Workshop and Research Seminar,Workshops are offered in all areas of speciali...,2 hours.,Approved for S/U grading only. May be repeated...,NaN,...,A,Open (Restricted),Conference,C5,02:00 PM,03:20 PM,F,317,David Kinley Hall,"Shea, J"
4348,2025,Spring,2025-sp,ECON,599,Thesis Research,Preparation of thesis required of all students...,0 TO 16 hours.,Approved for S/U grading only. May be repeated.,NaN,...,A,Open (Restricted),Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,NaN

### Puzzle 4.5:

Select **a random sample of 10% of the course sections** from your major:

In [19]:
mydf.sample(frac = 0.1)

,Year,Term,YearTerm,Subject,Number,Name,Description,Credit Hours,Section Info,Degree Attributes,...,Section Status,Enrollment Status,Type,Type Code,Start Time,End Time,Days of Week,Room,Building,Instructors
4259,2025,Spring,2025-sp,ECON,447,Economics of the Workplace,Application of economic theory to the relation...,3 OR 4 hours.,3 undergraduate hours. 4 graduate hours. Prere...,NaN,...,A,CrossListOpen (Restricted),Lecture-Discussion,LCD,09:30 AM,10:50 AM,MW,123,David Kinley Hall,"Sun, Y"
4307,2025,Spring,2025-sp,ECON,491,Topics in Econometrics,Special topics applying advanced econometrics ...,3 OR 4 hours.,3 undergraduate hours. 4 graduate hours. May b...,NaN,...,A,Closed,Lecture-Discussion,S7,11:00 AM,12:20 PM,TR,206,David Kinley Hall,"Toossi, A"
4196,2025,Spring,2025-sp,ECON,199,Undergraduate Open Seminar,Approved for both letter and S/U grading. May ...,0 TO 5 hours.,Approved for both letter and S/U grading. May ...,NaN,...,A,Open (Restricted),Seminar,SEM,ARRANGED,NaN,NaN,NaN,NaN,"Bilsbury, T"
4334,2025,Spring,2025-sp,ECON,590,Individual Study and Research,Directed reading and research. Approved for bo...,0 TO 4 hours.,Approved for both letter and S/U grading. May ...,NaN,...,A,Open (Restricted),Lecture-Discussion,S8,12:30 PM,03:20 PM,M,125,David Kinley Hall,"Hewings, G"
4280,2025,Spring,2025-sp,ECON,484,Law and Economics,Applications of economic theory to problems an...,2 TO 4 hours.,3 undergraduate hours. 2 or 4 graduate hours. ...,NaN,...,A,Closed,Lecture-Discussion,LCD,12:30 PM,01:50 PM,TR,125,David Kinley Hall,"Schultz, C"
4247,2025,Spring,2025-sp,ECON,420,International Economics,Introduction to the theory of international tr...,2 TO 4 hours.,3 undergraduate hours. 2 or 4 graduate hours. ...,NaN,...,A,Closed,Lecture-Discussion,LCD,11:00 AM,12:20 PM,TR,119,David Kinley Hall,"Dziuba, P"
4205,2025,Spring,2025-sp,ECON,203,Economic Statistics II,Continuation of ECON 202. Builds upon point an...,3 hours.,Students must have completed a course on proba...,NaN,...,A,Closed,Laboratory,LAB,09:00 AM,09:50 AM,F,144,Armory,"Choi, T;Jeziorski, W"
4344,2025,Spring,2025-sp,ECON,598,Workshop and Research Seminar,Workshops are offered in all areas of speciali...,2 hours.,Approved for S/U grading only. May be repeated...,NaN,...,A,Open (Restricted),Conference,CNF,02:00 PM,03:20 PM,MW,317,David Kinley Hall,"Yoo, H"
4319,2025,Spring,2025-sp,ECON,533,Microeconomic Theory II,Focusses on information and incentives in econ...,4 hours.,"Prerequisite: ECON 530, or equivalent; calculus.",NaN,...,A,Open (Restricted),Lecture,LEC,11:00 AM,12:20 PM,MW,215,David Kinley Hall,"Krasa, S"
4218,2025,Spring,2025-sp,ECON,210,Environmental Economics,"Same as ACE 210, ENVS 210, NRES 210, and UP 21...",3 hours.,"Same as ACE 210, ENVS 210, NRES 210, and UP 21...",Social & Beh Sci - Soc Sci course.,...,A,CrossListOpen,Lecture,LEC,03:00 PM,03:50 PM,MW,120,Architecture Building,"Damon, L"
4337,2025,Spring,2025-sp,ECON,590,Individual Study and Research,Directed reading and research. Approved for bo...,0 TO 4 hours.,Approved for both letter and S/U grading. May ...,NaN,...,A,Open (Restricted),Lecture-Discussion,S12,11:00 AM,12:20 PM,MW,215B,David Kinley Hall,"Creal, D"
4254,2025,Spring,2025-sp,ECON,437,Game Theory,Explores game theory and strategic decision ma...,3 OR 4 hours.,3 undergraduate hours. 4 graduate hours. Prere...,NaN,...,A,Closed,Lecture-Discussion,LCD,09:30 AM,10:50 AM,TR,119,David Kinley Hall,"Durandard, T"
4263,2025,Spring,2025-sp,ECON,460,Financial Economics,Study of a variety of financial economics topi...,3 OR 4 hours.,3 undergraduate hours. 4 graduate hours. Prere...,NaN,...,A,Closed,Lecture-Discussion,LCD,09:30 AM,10:50 AM,MW,317,David Kinley Hall,"Cho, M"
4285,2025,Spring,2025-sp,ECON,490,Topics in Economics,Special topics in advanced economics within a ...,3 OR 4 hours.,3 undergraduate hours. 4 graduate hours. May b...,NaN,...,A,Closed,Lecture-Discussion,S9,12:30 PM,01:50 PM,MW,317,David Kinley Hall,"Wang, C"
4202,2025,Spring,2025-sp,ECON,202,Economic Statistics I,Introduction of basic concepts in statistics i...,3 hours.,Credit is not given for ECON 202 if credit for...,Quantitative Reasoning I course.,...,A,Open,Laboratory,LAB,01:00 PM,01:50 PM,W,147,Armory,"Dutta, A;Schultz, C"
4230,2025,Spring,2025-sp,ECON,302,Inter Microeconomic Theory,Microeconomic analysis including value and dis...,3 hours.,Prerequisite: ECON 102 or equivalent. MATH 220...,NaN,...,A,Closed,Discussion/Recitation,DIS,11:00 AM,11:50 AM,F,226,Wohlers Hall,"DiIanni, I;Molina Gonzalez, C"
4313,2025,Spring,2025-sp,ECON,503,Econometrics,Develops a general methodological basis for se...,4 hours.,4 graduate hours. No professional credit. Prer...,NaN,...,A,Open (Restricted),Lecture,LEC,09:30 AM,10:50 AM,TR,123,David Kinley Hall,"Bera, A"
4291,2025,Spring,2025-sp,ECON,490,Topics in Economics,Special topics in advanced economics within a ...,3 OR 4 hours.,3 undergraduate hours. 4 graduate hours. May b...,NaN,...,A,Closed,Lecture-Discussion,S1,12:30 PM,01:50 PM,TR,113,David Kinley Hall,"Perry, M"
4170,2025,Spring,2025-sp,ECON,103,Macroeconomic Principles,Introduction to the theory of determination of...,3 hours.,NaN,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,01:00 PM,01:50 PM,F,119,David Kinley Hall,"Sadeghi, M;Vazquez, J"
4180,2025,Spring,2025-sp,ECON,103,Macroeconomic Principles,Introduction to the theory of determination of...,3 hours.,NaN,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,03:00 PM,03:50 PM,R,147,Armory,"Hoque, M;Vazquez, J"
4309,2025,Spring,2025-sp,ECON,491,Topics in Econometrics,Special topics applying advanced econometrics ...,3 OR 4 hours.,3 undergraduate hours. 4 graduate hours. May b...,NaN,...,A,Closed,Lecture-Discussion,S4,11:00 AM,12:20 PM,TR,219,David Kinley Hall,"Alonso Fontes, D"
4312,2025,Spring,2025-sp,ECON,503,Econometrics,Develops a general methodological basis for se...,4 hours.,4 graduate hours. No professional credit. Prer...,NaN,...,A,Open (Restricted),Discussion/Recitation,DIS,09:30 AM,10:50 AM,F,123,David Kinley Hall,"Rafi, J"

### ✔️ Checkpoint ✔️

There are no test cases for Part 4 (since everyone has different majors), but go double check your work! Share your results with your group. After that, there's just one section left to go! :)

<hr style="color: #DD3403;">

# Part 5: Growth of the IS major

The IS major is still a new relatively new major here at UIUC. The final puzzle is for you to analyze how much the IS major has grown since 2019.

### Puzzle 5.1: Loading the Course Catalog Dataset from 2019

Using the name `df2019` instead of `df`, load the "Fall 2019 Course Catalog Dataset" that can be found at the following URL:
```
http://waf-server-01.cs.illinois.edu/static/course-catalog-fa19.csv
```

In [20]:
df2019 = pd.read_csv("http://waf-server-01.cs.illinois.edu/static/course-catalog-fa19.csv")
df2019

,Year,Term,YearTerm,Subject,Number,Name,Description,Credit Hours,Section Info,Degree Attributes
0,2019,Fall,2019-fa,AAS,100,Intro Asian American Studies,Interdisciplinary introduction to the basic co...,3 hours.,NaN,"Social & Beh Sci - Soc Sci, and Cultural Studi..."
1,2019,Fall,2019-fa,AAS,105,Introduction to Arab American Studies,Interdisciplinary introduction to the basic co...,3 hours.,NaN,Cultural Studies - US Minority course.
2,2019,Fall,2019-fa,AAS,120,Intro to Asian Am Pop Culture,Introductory understanding of the way U.S. pop...,3 hours.,NaN,Cultural Studies - US Minority course.
3,2019,Fall,2019-fa,AAS,199,Undergraduate Open Seminar,May be repeated to a maximum of 6 hours.,1 TO 5 hours.,NaN,NaN
4,2019,Fall,2019-fa,AAS,200,U.S. Race and Empire,Invites students to examine histories and narr...,3 hours.,Same as LLS 200.,"Humanities - Hist & Phil, and Cultural Studies..."
...,...,...,...,...,...,...,...,...,...,...
8584,2019,Fall,2019-fa,ZULU,202,Elementary Zulu II,Continuation of ZULU 201 with introduction of ...,5 hours.,Same as AFST 252. Participation in the languag...,NaN
8585,2019,Fall,2019-fa,ZULU,403,Intermediate Zulu I,Survey of more advanced grammar; emphasis on i...,4 hours.,NaN,NaN
8586,2019,Fall,2019-fa,ZULU,404,Intermediate Zulu II,Continuation of ZULU 403; emphasis on increasi...,4 hours.,NaN,NaN
8587,2019,Fall,2019-fa,ZULU,405,Advanced Zulu I,Third year Zulu with emphasis on conversationa...,3 hours.,NaN,NaN
8588,2019,Fall,2019-fa,ZULU,406,Advanced Zulu II,Continuation of Zulu 405 with increased emphas...,3 hours.,NaN,NaN

### Puzzle 5.2: Data Analysis

In the following cells,
- Using the `df2019` dataset, select the rows where the subject is `IS`.
- Using the `df` dataset (this is the entire dataset containing the most recent data), select the rows where the subject is `IS`.
- Complete the reflection question below (Puzzle 5.3).  Feel free to write more code to answer it. Remember to work and chat with your group!

In [23]:
df2019[df2019.Subject == "IS"]

,Year,Term,YearTerm,Subject,Number,Name,Description,Credit Hours,Section Info,Degree Attributes
4843,2019,Fall,2019-fa,IS,107,Data Science Discovery,Same as CS 107 and STAT 107. See STAT 107,4 hours.,Same as CS 107 and STAT 107. See STAT 107,Quantitative Reasoning I course.
4844,2019,Fall,2019-fa,IS,199,Undergraduate Open Seminar,Undergraduate Open Seminar. May be repeated.,1 TO 5 hours.,NaN,NaN
4845,2019,Fall,2019-fa,IS,202,Social Aspects Info Tech,Same as INFO 202 and MACS 202. See INFO 202.,3 hours.,Same as INFO 202 and MACS 202. See INFO 202.,Social & Beh Sci - Soc Sci course.
4846,2019,Fall,2019-fa,IS,310,Computing in the Humanities,Explores use and application of technology to ...,3 hours.,NaN,NaN
4847,2019,Fall,2019-fa,IS,351,The Design of Usable Information Interfaces,Examines issues of Human Computer Interaction ...,3 hours.,Prerequisite: Sophomore standing.,NaN
...,...,...,...,...,...,...,...,...,...,...
4930,2019,Fall,2019-fa,IS,591,Practicum,Supervised field experience of professional-le...,2 hours.,2 graduate hours. No professional credit. Appr...,NaN
4931,2019,Fall,2019-fa,IS,592,Independent Study,Permits the intermediate or advanced student o...,2 TO 4 hours.,2 to 4 graduate hours. No professional credit....,NaN
4932,2019,Fall,2019-fa,IS,593,CAS Project,Individual study of a problem in library and i...,0 TO 8 hours.,0 to 8 graduate hours. No professional credit....,NaN
4933,2019,Fall,2019-fa,IS,594,Information Sciences Practice,Full-time or part-time practice of of any info...,0 hours.,0 graduate hours. No professional credit. Appr...,NaN
4934,2019,Fall,2019-fa,IS,599,Thesis Research,Individual study and research. 0 to 16 graduat...,0 TO 16 hours.,0 to 16 graduate hours. No professional credit...,NaN

In [24]:
df[df.Subject == "IS"]

,Year,Term,YearTerm,Subject,Number,Name,Description,Credit Hours,Section Info,Degree Attributes,...,Section Status,Enrollment Status,Type,Type Code,Start Time,End Time,Days of Week,Room,Building,Instructors
6404,2025,Spring,2025-sp,IS,100,Exploring the iSchool with a Human-Centered Lens,This course introduces students to the School ...,1 hours.,Prerequisite: Restricted to Majors Only; First...,NaN,...,A,Open (Restricted),Lecture-Discussion,LCD,11:00 AM,11:50 AM,T,126,Grad Sch of Lib & Info Science,"Kittl, K"
6405,2025,Spring,2025-sp,IS,101,Introduction to Information Sciences,This course provides an introduction to the fi...,3 hours.,NaN,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,11:00 AM,12:20 PM,R,12A,Grad Sch of Lib & Info Science,"Pintar, J"
6406,2025,Spring,2025-sp,IS,101,Introduction to Information Sciences,This course provides an introduction to the fi...,3 hours.,NaN,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,11:00 AM,12:20 PM,R,53,Grad Sch of Lib & Info Science,"Pintar, J"
6407,2025,Spring,2025-sp,IS,101,Introduction to Information Sciences,This course provides an introduction to the fi...,3 hours.,NaN,Social & Beh Sci - Soc Sci course.,...,A,Open (Restricted),Discussion/Recitation,DIS,09:30 AM,10:50 AM,R,12A,Grad Sch of Lib & Info Science,"Pintar, J"
6408,2025,Spring,2025-sp,IS,101,Introduction to Information Sciences,This course provides an introduction to the fi...,3 hours.,NaN,Social & Beh Sci - Soc Sci course.,...,A,Closed,Discussion/Recitation,DIS,12:30 PM,01:50 PM,R,12A,Grad Sch of Lib & Info Science,"Pintar, J"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6732,2025,Spring,2025-sp,IS,599,Thesis Research,Individual study and research. 0 to 16 graduat...,0 TO 16 hours.,0 to 16 graduate hours. No professional credit...,NaN,...,A,Open,Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,"Torvik, V"
6733,2025,Spring,2025-sp,IS,599,Thesis Research,Individual study and research. 0 to 16 graduat...,0 TO 16 hours.,0 to 16 graduate hours. No professional credit...,NaN,...,A,Open,Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,"Underwood, W"
6734,2025,Spring,2025-sp,IS,599,Thesis Research,Individual study and research. 0 to 16 graduat...,0 TO 16 hours.,0 to 16 graduate hours. No professional credit...,NaN,...,A,Open,Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,"Huang, Y"
6735,2025,Spring,2025-sp,IS,599,Thesis Research,Individual study and research. 0 to 16 graduat...,0 TO 16 hours.,0 to 16 graduate hours. No professional credit...,NaN,...,A,Open,Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,"Wang, Y"
6736,2025,Spring,2025-sp,IS,599,Thesis Research,Individual study and research. 0 to 16 graduat...,0 TO 16 hours.,0 to 16 graduate hours. No professional credit...,NaN,...,A,Open,Independent Study,IND,ARRANGED,NaN,NaN,NaN,NaN,"LeBlanc, Z"

In [0]:
# Feel free to add more code cells if needed by hovering over the area below the cell and pressing "+ Code"!

### Puzzle 5.3: Reflection on this Data Analysis

In the follow cell, **explain what you found** related to the growth of the IS program. In your explanation, make sure to **use actual data** (ex: by how much did it grow?)

*(We found that almost 2 thousand more courses were added to the IS cirriculum. 1,802 courses to be exact got added)*

<hr style="color: #DD3403;">

# Submission

You're almost done!  All you need to do is to commit your lab to GitHub:

1.  ⚠️ **Make certain to save your work.** ⚠️ To do this, go to **File => Save All**

2.  After you have saved, exit this notebook and follow the Canvas instructions to commit this lab to your Git repository!

3. Your TA will grade your submission and provide you feedback after the lab is due. :)