# Welcome to Lab: Favorites!

In this lab, you will explore several favorites of DISCOVERY, including the favorite things of your TA, Karle, and Wade!  This will **help you prepare for the mosaic project that was introduced in lecture on Wednesday**.

A few tips to remember:

- **You are not alone on your journey in learning programming!**  You have your lab TA, your CAs, your lab group, and the professors (Prof. Wade and Prof. Karle), who are all here to help you out!
- If you find yourself stuck for more than a few minutes, ask a neighbor or course staff for help!  When you are giving help to your neighbor, explain the **idea and approach** to the problem without sharing the answer itself so they can have the same **<i>ah-hah</i>** moment!
- We are here to help you!  Don't feel embarrassed or shy to ask us for help!

Let's get started!

In [1]:
# Meet your CAs and TA if you haven't already!
# ...first name is enough, we'll know who they are! :)
ta_name = "Aarush"
ca1_name = "Bella"
ca2_name = "Jonah"
ca3_name = ""


# Say hello to each other!
# - Groups of 3 are ideal :)
# - However, groups of 2 or 4 are fine too!
#
# Question of the Day (QOTD) to Ask Your Group: "Who is your favorite influencer?"
partner1_name = "neha"
partner1_netid = "nayak11"
partner1_favinfluencer = "Alix Earle"

partner2_name = "Antigoni"
partner2_netid = "agarbis2"
partner2_favinfluencer = "Alix Earle"

partner3_name = "Victoria"
partner3_netid = "vgazda2"
partner3_favinfluencer= "AlIx Earle"

# Which lab section are you in? Record it below! It should start with a Y and have 
# 2 numbers after the Y. If you're unsure - ask your TA/CAs!
lab_section = "Y05"

<hr style="color: #DD3403;">

# Part 1: Karle's Game Day!

One of Karle's favorite events is tailgating before Illini football games! The best part of tailgating is obviously the food and drinks 😉. Because Karle is an extrovert, she invites **many** people to her parties. For the upcoming games this fall, she needs to mix "mocktails" in gallons for all of her guests.  In this part of the lab, you will write a simulation to help simulate the possible drinks available at Karle's party.

A "mocktail" has three ingredients:
- A `mixer`, one of: `"cranberry juice"`, `"lime juice"`, `"lemonade"`, `"kool-aid"`, or `"red bull"` (gross!)
- A `fruit`, one of: `"watermelon"`, `"pineapple"`, `"lime"`, `"lemon"`, or `"cherry"` (yum!)
- A `core`, one of: `"sparkling water"`, `"sprite"`, and **add three other things** you should pick with your group to make five `"core"` component options!

### Puzzle 1.1: DataFrame
Create a DataFrame called `df` containing **10,000** simulations of possible "mocktail" combinations:

In [2]:
# Write your simulation:
import pandas as pd
import random
mixers = ["cranberry juice", "lime juice", "lemonade", "kool-aid", "red bull"]
fruits = ["watermelon", "pineapple", "lime", "lemon", "cherry"]
cores = ["sparkling water", "sprite", "soda", "water", "coke"]
data = []
for i in range(10000):
    mixer = random.choice(mixers)
    fruit = random.choice(fruits)
    core = random.choice(cores)
    d = {"mixer":mixer, "fruit":fruit, "core":core}
    data.append(d)
df = pd.DataFrame(data)

In [3]:
# view your DataFrame in this cell
df

           mixer       fruit             core
0       red bull      cherry           sprite
1     lime juice        lime           sprite
2       lemonade      cherry            water
3     lime juice        lime             coke
4     lime juice   pineapple             coke
...          ...         ...              ...
9995    red bull   pineapple  sparkling water
9996    red bull        lime           sprite
9997    lemonade   pineapple  sparkling water
9998    kool-aid  watermelon             coke
9999  lime juice       lemon             soda

[10000 rows x 3 columns]

### 🔬 Test Case Checkpoint 🔬

In [4]:
## == CHECKPOINT TEST CASES: Karle's Game Day ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
mixers = ["cranberry juice", "lime juice", "lemonade", "kool-aid", "red bull"]
fruits = ["watermelon", "pineapple", "lime", "lemon", "cherry"]
cores = ["sparkling water", "sprite"]
assert( 'df' in vars() ), "Your simulation did not populate a DataFrame variable named `df`."
assert( len(df) == 10000 ), "The length of your `df` is not 10000, check the value in your for-loop declaration."
assert( len(df.columns.to_list()) == 3 ), "Your DataFrame should contain 3 columns!"
assert( 'mixer' in df ), "Your DataFrame is missing a `mixer` column."
assert( 'fruit' in df ), "Your DataFrame is missing a `fruit` column."
assert( 'core' in df ), "Your DataFrame is missing a `core` column."
for m in mixers:
    assert ( m in list(df['mixer']) ), f"Your DataFrame is missing the mixer {m}."
for f in fruits:
    assert ( f in list(df['fruit']) ), f"Your DataFrame is missing the fruit {f}."
for c in cores:
    assert ( c in list(df['core']) ), f"Your DataFrame is missing the core {c}."

assert( len(set(df['core'])) == 5 ), "Your DataFrame does not return five unique core components."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 1.2: Simulated Probability of a True Mocktail

Karle is incredibly suspicious of the extra ingredients you picked for her, so we consider a "true mocktail" to be a drink made with a core of `"sparkling water"` or `"sprite"` only.  Calculate the estimated probability that a randomly created drink is a "true mocktail" the variable `P_trueMocktail`:

In [5]:
true_mocktail = df[(df["core"] == "sparkling water") | (df["core"] == "sprite")]
P_trueMocktail = len(true_mocktail)/len(df)
P_trueMocktail

0.3941

### Puzzle 1.3: Simulated Probability of Red Bull!

Many people feel the combination of energy drinks with other drinks is gross! Calculate the estimated probability that a randomly created drink has **red bull and sprite** or **red bull and sparkling water** in the variable `P_redBullCombo`. Use your simulation data to do this!

In [6]:
redbull_combo = df[((df["mixer"]=="red bull") & (df["core"] == "sprite")) | ((df["mixer"]=="red bull") & (df["core"] == "sparkling water"))]
P_redBullCombo = len(redbull_combo)/len(df)
P_redBullCombo

0.0709

### 🔬 Test Case Checkpoint 🔬

In [7]:
## == CHECKPOINT TEST CASES: Mocktail Probabilities ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert( 0.38 <= P_trueMocktail and 0.42 >= P_trueMocktail ), "You've calculated `P_trueMocktail` incorrectly."
assert( 0.07 <= P_redBullCombo and 0.095 >= P_redBullCombo ), "You've calculated `P_redBullCombo` incorrectly."
'''
NOTE: 
These boundary values were obtained by running 10,000 correct simulations and finding the max, min probability of ALL those runs. 
There is still a chance, albeit *extremely* low, that a student fails this test case with correct code. 
If the value is suspiciously close, try running all cells again. 
'''

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

<hr style="color: #DD3403;">

# Part 2: Wade's Game Night

While extroverts love their parties, Wade would rather be playing his favorite game in his basement with his partner at home!  One of his favorite games is a table-top game called Dominion.

The only thing you need to know is that your starting hand in Dominion is **five cards** drawn from a starting deck of ten cards.  The deck of ten cards is made up of the following cards:

- There are exactly 7 "coppers" in the starting deck
- There are exactly 3 "estates" in the starting deck

Here's the whole starting deck from which you'll randomly choose five cards:

---

![starting-deck.png](./notebook-images/starting-deck.png)

---

### Puzzle 2.1: Function

In the cell below, write a function that returns the number of coppers in a random starting hand (remember, a starting hand is 5 cards drawn without replacement). This function should be named `coppersInStartingHand`. To help, we have given you code that creates a DataFrame of of 10 cards (7 coppers and 3 estates).

In [8]:
# Try displaying this DataFrame on a new line!
deck = pd.DataFrame({"card": ['estate', 'estate', 'estate', 'copper', 'copper', 'copper', 'copper', 'copper', 'copper', 'copper']})
deck

     card
0  estate
1  estate
2  estate
3  copper
4  copper
5  copper
6  copper
7  copper
8  copper
9  copper

In [9]:
# Write your function here (hint: how do we randomly select from a dataframe?)
def coppersInStartingHand(deck):
    starting_hand = deck.sample(n=5)
    number_coppers = sum(starting_hand["card"] == "copper")
    return number_coppers

In [10]:
# Call the function to make sure it works
coppersInStartingHand(deck)

3

### Puzzle 2.2: DataFrame from Simulation

Using the `coppersInStartingHand` function, create a DataFrame of 10,000 starting hands of five cards. In your DataFrame, make sure you have at least the following two columns:
- `coppers`, the total number of coppers in your starting hand
- `estates`, the total number of estates in your starting hand 

To solve this, think about the relationship between the number of coppers and the number of estates.  For example, if you have 4 coppers, how many estates must you have?

Make sure to call your DataFrame `df_startingHands`.

In [11]:
# Create your simulation and `df_startingHands`:
data = []
for i in range(10000):
    coppers = coppersInStartingHand(deck)
    estates = 5 - coppers
    d = {"coppers": coppers, "estates":estates}
    data.append(d)
df_startingHands = pd.DataFrame(data)

In [12]:
# view your DataFrame in this cell
df_startingHands

      coppers  estates
0           4        1
1           3        2
2           3        2
3           3        2
4           3        2
...       ...      ...
9995        3        2
9996        3        2
9997        4        1
9998        3        2
9999        3        2

[10000 rows x 2 columns]

### 🔬 Test Case Checkpoint 🔬

In [13]:
## == CHECKPOINT TEST CASES: Wade's Game Night ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
copper_counts = [2, 3, 4, 5]
estate_counts = [0, 1, 2, 3] 
assert( 'df_startingHands' in vars() ), "Your simulation did not populate a DataFrame variable named `df_startingHands`."
assert( len(df_startingHands) == 10000 ), "The length of your DataFrame is not 10000, check the value in your for-loop declaration."
assert( len(df_startingHands.columns.to_list()) == 2 ), "Your `df_startingHands` should contain 2 columns!"
assert( 'coppers' in df_startingHands ), "Your DataFrame is missing a `coppers` column."
assert( 'estates' in df_startingHands ), "Your DataFrame is missing an `estates` column."
for i in copper_counts:
    assert ( i in list(df_startingHands['coppers']) ), f"Your DataFrame is missing instances in which you have {i} coppers in your starting hand. Check your starting hand calculations or your dictionary variables."
for i in estate_counts:
    assert ( i in list(df_startingHands['estates']) ), f"Your DataFrame is missing instances in which you have {i} estates in your starting hand. Check your starting hand calculations or your dictionary variables."

assert ( set(df_startingHands['coppers'] + df_startingHands['estates']) == {5}), "A starting hand should always have 5 cards. Your simulation produced an instance where this is not true."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 2.3: A Lucky Start

One of the luckiest starting hands is to have **five coppers**.  What is the **simulated** probability of Wade starting with five coppers? *Hint: use your DataFrame `df_startingHands` for your calculation!*

In [14]:
P_fiveCoppers = len(df_startingHands[df_startingHands["coppers"] == 5])/ len(df_startingHands)
P_fiveCoppers

0.0801

### 🔬 Test Case Checkpoint 🔬

In [15]:
## == CHECKPOINT TEST CASES: A Lucky Start ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert( 0.07 <= P_fiveCoppers and 0.1 >= P_fiveCoppers ), "You've calculated `P_fiveCoppers` incorrectly."
'''
NOTE: 
These boundary values were obtained by running 10,000 correct simulations and finding the max, min probability of ALL those runs. 
There is still a chance, albeit *extremely* low, that a student fails this test case with correct code. 
If the value is suspiciously close, try running all cells again. 
'''

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

<hr style="color: #DD3403;">

# Part 3: Using Images

Up until now, we have used **organized, well-structured data** in DISCOVERY.  However, data can be found everywhere, and in this lab, we'll begin to explore the data that doesn't come to us in a CSV!

Specifically, let's look at an **image**!  A computer represents an image as a 2D grid of **pixels** where each pixel is a single color.  Each dot on your computer's screen a pixel, so here's a **really small** image that is 3 pixels by 3 pixels: ![sample image](./notebook-images/sample.png)

Here is the that same 3x3 image, **zoomed in at 50x**:


![Color](./notebook-images/sample-50x.png)

### Puzzle 3.1: Loading the Image into a DataFrame

We will need to use Python to help us process large images, but we will use the example 3x3 image to understand how to work with images!  For this lab, we have provided the function for you to load images as a DataFrame.

- Use `import DISCOVERY` to import the DISCOVERY library
- Use `DISCOVERY.df_image("sample.png")` to load the image and return the data in the form of a DataFrame
- Save your image DataFrame you've loaded as `df_pixels`

In [25]:
# Load the image into a DataFrame `df_pixels`:
import DISCOVERY
df_pixels = DISCOVERY.df_image("sample.png")

### 🔬 Test Case Checkpoint 🔬

In [26]:
## == CHECKPOINT TEST CASES: Using Images ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert( len(df_pixels) == 9 ), "The length of your `df_pixels` should be 9 - there's 9 pixels in the sample.png!"
assert( len(df_pixels.columns.to_list() ) == 5 ), "There should be five columns in your `df_pixels`."
for col in ['x', 'y', 'r', 'g', 'b']:
    assert ( col in df_pixels ), f"Your `df_pixels` is missing the {col} column. Make sure you're using the `DISCOVERY.df_image()` function!"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

## Understanding the DataFrame

In your DataFrame above, every pixel has five values:
- An `x` value, for the **x** (horizontal) position, starting with `0` in the top-left
- A `y` value, for the **y** (vertical) position, starting with `0` in the top-left
- An `r` value, for the amount of **red** color in the image (`0` means no red, `255` means 100% red)
- A `g` value, for the amount of **green** color in the image (`0` - `255`)
- A `b` value, for the amount of **blue** color in the image (`0` - `255`)

In the image above, the top-left cell is blue.  Let's see what that looks like in data:

In [27]:
df_pixels[ (df_pixels.x == 0) & (df_pixels.y == 0) ]

   x  y  r  g    b
0  0  0  0  0  255

...the color value for `(x = 0, y = 0)` is all blue (`b = 255`) with no other colors added.  Moving to the right to `x == 1`:

In [28]:
df_pixels[ (df_pixels.x == 1) & (df_pixels.y == 0) ]

   x  y    r    g    b
3  1  0  255  255  255

...the color value for `(x = 1, y = 0)` is all the colors (`r`, `g` and `b` are all `255`).  Since computers create colors with light ("additive colors"), the combination of all the colors makes a white color.

### Puzzle 3.2: Finding all the white pixels

Just above this section, you learned how a white pixel is represented in data.  Create a new DataFrame, `df_white`, that contains all of the white pixels in the sample image **without using the `x` and `y` columns**:

In [29]:
df_white = df_pixels[(df_pixels["r"] == 255) & (df_pixels["g"] == 255) & (df_pixels["b"] == 255)]
df_white

   x  y    r    g    b
2  0  2  255  255  255
3  1  0  255  255  255
7  2  1  255  255  255

### Puzzle 3.3: Finding all the "primarily red" pixels

Find all the pixels that are "primarily red", where a "primarily red" pixel has more red than green **AND** more red than blue.  Store all the "primarily red" pixels in the DataFrame `df_primarily_red`.

In [30]:
df_primarily_red = df_pixels[(df_pixels["r"] > df_pixels["g"]) & (df_pixels["r"] > df_pixels["b"])]
df_primarily_red

   x  y    r   g   b
5  1  2  255  85  46
6  2  0  255   0   0

### 🔬 Test Case Checkpoint 🔬

In [31]:
## == CHECKPOINT TEST CASES: Finding Pixels ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert( 'df_white' in vars() ), "Make sure your DataFrame of white pixels is named `df_white`."
assert( 'df_primarily_red' in vars() ), "Make sure your DataFrame of red pixels is named `df_primarily_red`."
assert( len(df_white) == 3 ), "Your `df_white` does not contain all three white pixels in the sample image."
assert( (df_white['r'] == 255).all() and (df_white['g'] == 255).all() and (df_white['b'] == 255).all() ), "Your `df_white` contains non-white pixels."
assert( len(df_primarily_red) == 2 ), "Your `df_primarily_red` does not contain the two 'primarily red' pixels in the sample image."
assert( set(df_primarily_red['x'] + df_primarily_red['y']) == {2, 3} ), "Your `df_primarily_red` does not contain the two 'primarily red' pixels in the sample image."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

<hr style="color: #DD3403;">

# Part 4: Your Lab-Specific Image with your TAs and CAs

### Puzzle 4.1: Loading your Lab Image

Before your section, your TA -- with the help of the CAs -- picked an image for you to do analysis on!

- Navigate to the image by typing your lab's image URL into a browser and save the image to your computer.
- Place the image in the same folder as this lab (`lab_favorites`).
- Load the image into a DataFrame `df_lab_image` using `DISCOVERY.df_image(file name)`.

In [37]:
# Load the image your TA chose for you into a DataFrame:
df_lab_image = DISCOVERY.df_image("mehmet-a.jpg")
df_lab_image

           x    y    r    g    b
0          0    0  165  136  104
1          0    1  165  136  104
2          0    2  165  136  104
3          0    3  165  136  104
4          0    4  165  136  104
...      ...  ...  ...  ...  ...
999745  1332  745  208  188  163
999746  1332  746  208  188  163
999747  1332  747  209  189  164
999748  1332  748  209  189  164
999749  1332  749  210  190  165

[999750 rows x 5 columns]

### Puzzle 4.2: "Primary Color"

Using the idea of "primary red" pixels, we will extend the idea to "primary red", "primary green", or "primary blue".  In the following three sections, find the **percentage of pixels** that are primarily red, green, and blue, storing in the **decimal variables** `percent_primarily_r`, `percent_primarily_g`, and `percent_primarily_b`:

In [34]:
# Find the percentage of primarily red pixels:
percent_primarily_r = df_lab_image[(df_lab_image["r"] > df_lab_image["g"]) & (df_lab_image["r"] > df_lab_image["b"])]
percent_primarily_r

           x    y    r    g    b
0          0    0  165  136  104
1          0    1  165  136  104
2          0    2  165  136  104
3          0    3  165  136  104
4          0    4  165  136  104
...      ...  ...  ...  ...  ...
999745  1332  745  208  188  163
999746  1332  746  208  188  163
999747  1332  747  209  189  164
999748  1332  748  209  189  164
999749  1332  749  210  190  165

[845430 rows x 5 columns]

In [35]:
# Find the percentage of primarily green pixels:
percent_primarily_g = df_lab_image[(df_lab_image["g"] > df_lab_image["r"]) & (df_lab_image["g"] > df_lab_image["b"])]
percent_primarily_g

           x    y    r    g    b
193303   257  553   10   12   11
193305   257  555   78   79   74
194803   259  553   18   20   19
195553   260  553   15   17   16
196302   261  552   38   40   39
...      ...  ...  ...  ...  ...
766844  1022  344  237  238  224
766845  1022  345  249  250  236
766847  1022  347  253  255  239
766848  1022  348  251  252  236
766849  1022  349  254  255  239

[825 rows x 5 columns]

In [36]:
# Find the percentage of primarily blue pixels:
percent_primarily_b = df_lab_image[(df_lab_image["b"] > df_lab_image["r"]) & (df_lab_image["b"] > df_lab_image["g"])]
percent_primarily_b

          x    y   r   g   b
123624  164  624  61  54  62
123625  164  625  62  55  63
123626  164  626  64  57  65
123627  164  627  65  58  66
124368  165  618  77  70  78
...     ...  ...  ..  ..  ..
738314  984  314  66  66  68
738315  984  315  65  65  67
738316  984  316  63  63  65
738317  984  317  62  62  64
738318  984  318  63  63  65

[147211 rows x 5 columns]

### Puzzle 4.3: Average Color

Finally, find the average color of the entire image.  The average color will have three components: the average red, the average green, and the average blue. Store them in the variables `avg_red`, `avg_green`, and `avg_blue`.

In [38]:
# Find the average red:
avg_red = len(percent_primarily_r)/len(df_lab_image)
avg_red

0.8456414103525881

In [39]:
# Find the average green:
avg_green = len(percent_primarily_g)/len(df_lab_image)
avg_green

0.0008252063015753939

In [40]:
# Find the average blue:
avg_blue = len(percent_primarily_b)/len(df_lab_image)
avg_blue

0.14724781195298825

### See the Average Color

Colors are presented in code as a tuple, `rgb(1, 2, 3)`.  Run the following code to see the average color represented as a tuple, and to see a Google search where you can view it yourself!

In [41]:
color = f"rgb({round(avg_red)}, {round(avg_green)}, {round(avg_blue)})"

print(f"Average color: {color}")
color = color.replace(" ", "")
print(f"See it on Google color picker: https://www.google.com/search?q={color}&")

Average color: rgb(1, 0, 0)
See it on Google color picker: https://www.google.com/search?q=rgb(1,0,0)&

### Puzzle 4.4: Average Color of a Subset

Finally, using the same image, find the average blue color of the 10x10 square starting at x = 100 and y = 100. Store it in the variable `avg_blue_10_by_10`.

InvalidIndexError: (slice(100, 110, None), slice(100, 110, None), 2)

### 🔬 Test Case Checkpoint 🔬

In [43]:
## == CHECKPOINT TEST CASES: Average Color of a Subset ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert( isinstance(avg_blue_10_by_10, float) ), "Your average pixel color a be decimal (float) variable."
assert( avg_blue_10_by_10 >= 0 and avg_blue_10_by_10 <= 255 ), "The average blue value should be between 0 and 255."

import math
w = df_lab_image.x.max()+1
h = df_lab_image.y.max()+1
b = df_lab_image.values[:,4]
avgb = b[[i*h + j for i in range(w) for j in range(h) if all(n - 100 in range(10) for n in {i, j})]].mean()

assert( math.isclose(avg_blue_10_by_10, avgb) ), "Your average blue color of the 10x10 square is incorrect."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")
print("\u26A0 This test cases only checks Part 4.4, so double-check Parts 4.2 and 4.3! \u26A0")

NameError: name 'avg_blue_10_by_10' is not defined

### Analysis: 

**Question 1:** Looking at Part 2, what would happen to the simulated probability of having a starting hand of five coppers if we took out 2 estate cards from the starting deck (leaving 7 coppers and 1 estate in the starting deck)? Justify your answer.

The simulated probability of having a starting hand of five coppers would increase because we used to have 10 total cards. but after we take out 2 estate cards it brings the total cards down to 8. The probability of 5/8 is higher than 5/10 which also helps support my answer that the simulated probability of having a staring hand of 5 coppers would increase.

**Question 2:** Is the average color in an image always the most commonly occurring color? If not, what does the "average color" tell us?

The average color in an image is not always the most commonly occuring color. The average color in an image is just the mean of all pixel colors, that color doesn't even have to exist in the original image.

*(✏️ Edit this cell to replace this text with your answers to the 2 questions. Please write in complete sentences. ✏️)*

<hr style="color: #DD3403;">

# Submission

You're almost done!  All you need to do is to commit your lab to GitHub:

1.  ⚠️ **Make certain to save your work.** ⚠️ To do this, go to **File => Save All**

2.  After you have saved, exit this notebook and follow the Canvas instructions to commit this lab to your Git repository!

3. Your TA will grade your submission and provide you feedback after the lab is due. :)